language: python
stages:
  - install
  - test_install
  - deploy

jobs:
  include:
    # Deploy to PyPi
    - stage: deploy
      name: "Deploy to PyPi"
      install: pip install -U pip setuptools wheel
      script: skip
      deploy: &pypi
        provider: pypi
        user: "__token__"
        password: $pypi_token
