language: python
stages:
  - install
  - test_install
  - deploy

jobs:
  include:
    # Test install the module
    - stage: install
      install: pip install -U pip setuptools wheel
      name: "Setup test"
      python: "3.6"
      script:
        - python setup.py install

    # Test the install of the module
    - stage: test_install
      install: pip install -U pip setuptools wheel
      name: "Test setup"
      python: "3.6"
      script:
        - python tests/travis_test_install.py


    # Deploy to PyPi if all tests pass and change was done on master.
    - stage: deploy
      name: "Deploy to PyPi"
      install: pip install -U pip setuptools wheel
      script: skip
      deploy: &pypi
        provider: pypi
        user: "__token__"
        password: $pypi_token
